INPUT DADA
INPUT_PATH dada
DM_MIN 50
DM_MAX 3000
WIDTH_MIN 1
WIDTH_MAX 128
SNR 7.0
GULP 16384
OUTPUT SOCKET
HOST 10.42.0.90
PORT 13345
BEAM0 256
BEAM_OFFSET 0
GPU 0
OUTPUTPATH /home/ubuntu/data/test0.out
SPECFLAGS /home/ubuntu/data/spec0.out
BEAMFLAGS /home/ubuntu/data/beam0.out
SCRUNCH 3
128 2 6.0 1
8 8 7.0 1
128 1 6.0 1