INPUT CANDIDATE
INPUT_PATH /dataz/dsa110/candidates/250217gqlc/Level2/filterbank/250217gqlc_28.fil
DM_MIN 50
DM_MAX 3000
WIDTH_MIN 1
WIDTH_MAX 128
SNR 8.0
GULP 16384
OUTPUT FILE
HOST 10.42.0.90
PORT 12345
GPU 1
BEAM0 0
BEAM_OFFSET 0
OUTPUTPATH test.out
SPECFLAGS spec.out
BEAMFLAGS beam.out
SCRUNCH 2
16 4 4.0 1
128 32 4.0 1
