FLAG1 48
FLAG2 96
INPUT DADA
INPUT_PATH dada
DM_MIN 50
DM_MAX 3000
WIDTH_MIN 1
WIDTH_MAX 128
SNR 7.5
GULP 16384
OUTPUT SOCKET
HOST 10.42.0.90
PORT 12346
BEAM0 64
BEAM_OFFSET 64
GPU 1
OUTPUT_BANDPASS	2
OUTPUTPATH /home/ubuntu/data/test1.out
SPECFLAGS /home/ubuntu/data/spec1.out
BEAMFLAGS /home/ubuntu/data/beam1.out
SCRUNCH 3
128 2 6.0 1
8 8 6.0 1
128 8 4.5 1