FLAG1 0
FLAG2 40
INPUT FILTERBANK
INPUT_PATH /dataz/dsa110/training/corr01_test_0_828.fil
DM_MIN 50
DM_MAX 3000
WIDTH_MIN 1
WIDTH_MAX 128
SNR 7.3
GULP 16384
OUTPUT FILE
OUTPUTPATH test.out
SPECFLAGS spec.out
BEAMFLAGS beam.out
GPU 0
SPEC_MIN -0.03
SPEC_MAX 0.08
OUTPUT_BANDPASS 1
OUTPUTPATH /home/ubuntu/data/test0.out
SPECFLAGS /home/ubuntu/data/spec0.out
BEAMFLAGS /home/ubuntu/data/beam0.out
SCRUNCH 2
4 4 4.0 1
1 16 4.0 1
