FLAG1 0
FLAG2 40
INPUT DADA
INPUT_PATH dada
DADA_OUT fada
DM_MIN 20
DM_MAX 2000
WIDTH_MIN 1
WIDTH_MAX 65
SNR 6.7
GULP 16384
OUTPUT SOCKET
HOST 10.42.0.90
PORT 13345
BEAM0 256
BEAM_OFFSET 0
SPEC_MIN -0.07
SPEC_MAX 0.08
GPU 0
OUTPUT_BANDPASS	1
OUTPUTPATH /home/ubuntu/data/test0.out
SPECFLAGS /home/ubuntu/data/spec0.out
BEAMFLAGS /home/ubuntu/data/beam0.out
SCRUNCH 2
4 4 4.0 1
1 16 4.0 1
