FLAG1 0
FLAG2 40
INPUT DADA
INPUT_PATH dada
DADA_OUT fada
DM_MIN 50
DM_MAX 2500
WIDTH_MIN 1
WIDTH_MAX 128
SNR 6.8
GULP 16384
OUTPUT SOCKET
HOST 10.42.0.90
PORT 13345
BEAM0 256
BEAM_OFFSET 0
SPEC_MIN -30.
SPEC_MAX 80.
GPU 0
OUTPUT_BANDPASS	1
OUTPUTPATH /home/ubuntu/data/test0.out
SPECFLAGS /home/ubuntu/data/spec0.out
BEAMFLAGS /home/ubuntu/data/beam0.out
SCRUNCH 2
4 4 4.0 1
1 16 4.0 1
