FLAG1 0
FLAG2 40
INPUT DADA
INPUT_PATH dada
DADA_OUT eada
DM_MIN 50
DM_MAX 2500
WIDTH_MIN 1
WIDTH_MAX 128
SNR 6.8
GULP 16384
OUTPUT SOCKET
HOST 10.42.0.90
PORT 12346
BEAM0 64
BEAM_OFFSET 64
SPEC_MIN -30.
SPEC_MAX 80.
GPU 1
OUTPUT_BANDPASS	2
OUTPUTPATH /home/ubuntu/data/test1.out
SPECFLAGS /home/ubuntu/data/spec1.out
BEAMFLAGS /home/ubuntu/data/beam1.out
