FLAG1 0
FLAG2 40
INPUT DADA
INPUT_PATH dada
DADA_OUT eada
DM_MIN 20
DM_MAX 2000
WIDTH_MIN 1
WIDTH_MAX 65
SNR 6.5
GULP 16384
OUTPUT SOCKET
HOST 10.42.0.90
PORT 12346
BEAM0 64
BEAM_OFFSET 64
SPEC_MIN -0.07
SPEC_MAX 0.08
GPU 1
OUTPUT_BANDPASS	2
OUTPUTPATH /home/ubuntu/data/test1.out
SPECFLAGS /home/ubuntu/data/spec1.out
BEAMFLAGS /home/ubuntu/data/beam1.out
SCRUNCH 2
4 4 4.0 1
1 16 4.0 1
