# configuration for correlator and beamformer
buffers:
  - k: dada
    b: 94371840
    n: 8
    c: 0    
  - k: dbda
    b: 94371840 
    n: 8
    c: 1
  - k: dcda
    b: 94371840 
    n: 8
    c: 1
  - k: ddda
    b: 94371840 
    n: 8
    c: 1
  - k: eaea
    b: 94371840 
    n: 300
    c: 1
  - k: fafa
    b: 2831155200
    n: 2
    c: 1
  - k: eada
    b: 402653184
    n: 4
    c: 1
  - k: fada
    b: 51118080
    n: 4
    c: 1
  - k: bada
    b: 1996800
    n: 40
    c: 0
  - k: cada
    b: 6291456
    n: 4
    c: 1
routines:
  - name: dsaX_store
    cmd: /home/ubuntu/proj/dsa110-shell/dsa110-xengine/src/dsaX_store
    args: -c 11 -k fafa
  - name: dsaX_trigger
    cmd: /home/ubuntu/proj/dsa110-shell/dsa110-xengine/src/dsaX_trigger
    args: -c 11 -i 127.0.0.1 -d -j eaea -o fafa 
  - name: meridian_fringestop
    cmd: /home/ubuntu/anaconda3/envs/casa/bin/python
    args: /home/ubuntu/proj/dsa110-shell/dsa110-meridian-fs/dsamfs/meridian_fringestop.py /home/ubuntu/proj/dsa110-shell/dsa110-xengine/scripts/dsa_parameters.yaml /home/ubuntu/data 
  - name: dsaX_dbnic
    cmd: /home/ubuntu/proj/dsa110-shell/dsa110-xengine/src/dsaX_dbnic
    args: -i cada -d
    hostargs:
      corr00: -g 0
      corr02: -g 1
      corr03: -g 2
      corr04: -g 3
      corr05: -g 4
      corr06: -g 5
      corr07: -g 6
      corr08: -g 7
      corr09: -g 8
      corr10: -g 9
      corr11: -g 10
      corr12: -g 11
      corr13: -g 12
      corr14: -g 13
      corr15: -g 14
      corr16: -g 15
  - name: dsaX_wrangle
    cmd: /home/ubuntu/proj/dsa110-shell/dsa110-xengine/src/dsaX_wrangle
    args: -i fada -o bada
  - name: dsaX_beamformer
    cmd: /home/ubuntu/proj/dsa110-shell/dsa110-xengine/src/dsaX_beamformer
    args: -c 30 -f /home/ubuntu/proj/dsa110-shell/dsa110-xengine/utils/antennas.out -a /home/ubuntu/proj/dsa110-shell/dsa110-xengine/scripts/flagants.dat -i ddda -o cada 
    hostargs:
      corr00: -z 1498.75
      corr02: -z 1487.03125
      corr03: -z 1475.3125
      corr04: -z 1463.59375
      corr05: -z 1451.875
      corr06: -z 1440.15625
      corr07: -z 1428.4375
      corr08: -z 1416.71875
      corr09: -z 1405.0
      corr10: -z 1393.28125
      corr11: -z 1381.5625
      corr12: -z 1369.84375
      corr13: -z 1358.125
      corr14: -z 1346.40625
      corr15: -z 1334.6875
      corr16: -z 1322.96875
  - name: dsaX_xgpu
    cmd: /home/ubuntu/proj/dsa110-shell/dsa110-xengine/src/dsaX_xgpu
    args: -t 8 -i eada -o fada -c 31
  - name: dsaX_reorder_raw
    cmd: /home/ubuntu/proj/dsa110-shell/dsa110-xengine/src/dsaX_reorder_raw
    args: -t 16 -i dbda -o eada
  - name: dsaX_split
    cmd: /home/ubuntu/proj/dsa110-shell/dsa110-xengine/src/dsaX_split
    args: -i dcda -o ddda -j eaea -c 19 -b -m 
  - name: dsaX_split
    cmd: /home/ubuntu/proj/dsa110-shell/dsa110-xengine/src/dsaX_split
    args: -i dada -o dbda -j dcda -c 19 -b -m -s
  - name: dsaX_capture
    cmd: /home/ubuntu/proj/dsa110-shell/dsa110-xengine/src/dsaX_capture
    args: -c 1 -i 127.0.0.1 -o dada -f /home/ubuntu/proj/dsa110-shell/dsa110-xengine/src/correlator_header_dsaX.txt
    hostargs:
      corr00: -j 10.41.0.69
      corr02: -j 10.41.0.87
      corr03: -j 10.41.0.91
      corr04: -j 10.41.0.117
      corr05: -j 10.41.0.79
      corr06: -j 10.41.0.58
      corr07: -j 10.41.0.116
      corr08: -j 10.41.0.99
      corr09: -j 10.41.0.66
      corr10: -j 10.41.0.122
      corr11: -j 10.41.0.121
      corr12: -j 10.41.0.61
      corr13: -j 10.41.0.60
      corr14: -j 10.41.0.115
      corr15: -j 10.41.0.113
      corr16: -j 10.41.0.83
