# configuration for correlator and beamformer
buffers:
  - k: dada
    b: 75497472
    n: 16
    c: 0    
  - k: dbda
    b: 75497472 
    n: 8
    c: 1
  - k: dcda
    b: 75497472 
    n: 8
    c: 1
  - k: eada
    b: 402653184
    n: 8
    c: 1
  - k: fada
    b: 51118080
    n: 4
    c: 1
  - k: bada
    b: 1996800
    n: 40
    c: 0
  - k: cada
    b: 1572864
    n: 8
    c: 1
routines:
  - name: meridian_fringestop
    cmd: python
    args: /home/ubuntu/proj/dsa110-shell/dsa110-meridian-fs/dsamfs/meridian_fringestop.py /home/ubuntu/proj/dsa110-shell/dsa110-xengine/scripts/dsa_parameters.yaml /home/ubuntu/data 
  - name: dsaX_dbnic
    cmd: /home/ubuntu/proj/dsa110-shell/dsa110-xengine/src/dsaX_dbnic
    args: -i cada -d
    hostargs:
      corr01: -g 0
      corr02: -g 1
      corr03: -g 2
      corr04: -g 3
      corr05: -g 4
      corr06: -g 5
      corr07: -g 6
      corr08: -g 7
      corr09: -g 8
      corr10: -g 9
      corr11: -g 10
      corr12: -g 11
      corr13: -g 12
      corr14: -g 13
      corr15: -g 14
      corr16: -g 15
  - name: dsaX_wrangle
    cmd: /home/ubuntu/proj/dsa110-shell/dsa110-xengine/src/dsaX_wrangle
    args: -i fada -o bada
  - name: dsaX_beamformer
    cmd: /home/ubuntu/proj/dsa110-shell/dsa110-xengine/src/dsaX_beamformer
    args: -c 30 -f /home/ubuntu/proj/dsa110-shell/dsa110-xengine/utils/antennas.out -i dcda -o cada
  - name: dsaX_xgpu
    cmd: /home/ubuntu/proj/dsa110-shell/dsa110-xengine/src/dsaX_xgpu
    args: -t 8 -i eada -o fada -c 31
  - name: dsaX_reorder_raw
    cmd: /home/ubuntu/proj/dsa110-shell/dsa110-xengine/src/dsaX_reorder_raw
    args: -t 16 -i dbda -o eada
  - name: dsaX_split
    cmd: /home/ubuntu/proj/dsa110-shell/dsa110-xengine/src/dsaX_split
    args: -i dada -o dbda -j dcda -c 19 -b -m
  - name: dsaX_capture
    cmd: /home/ubuntu/proj/dsa110-shell/dsa110-xengine/src/dsaX_capture
    args: -c 1 -i 127.0.0.1 -o dada -f /home/ubuntu/proj/dsa110-shell/dsa110-xengine/src/correlator_header_dsaX.txt
    hostargs:
      corr01: -j 10.41.0.62
      corr02: -j 10.41.0.63
      corr03: -j 10.41.0.54
      corr04: -j 10.41.0.55
      corr05: -j 10.41.0.58
      corr06: -j 10.41.0.56
      corr07: -j 10.41.0.57
      corr08: -j 10.41.0.59
      corr09: -j 10.41.0.60
      corr10: -j 10.41.0.61
      corr11: -j 10.41.0.64
      corr12: -j 10.41.0.65
      corr13: -j 10.41.0.66
      corr14: -j 10.41.0.68
      corr15: -j 10.41.0.75
      corr16: -j 10.41.0.79
