# configuration for correlator with original file writing
buffers:
  - k: dada
    b: 268435456
    n: 4
    c: 0
  - k: eada
    b: 268435456
    n: 4
    c: 0
  - k: fada
    b: 268435456
    n: 4
    c: 0
  - k: bada
    b: 268435456
    n: 4
    c: 0
routines:
  - name: heimdall
    cmd: /home/ubuntu/proj/dsa110-shell/dsa110-mbheimdall/bin/heimdall
    args: -k bada -gpu_id 0 -nsamps_gulp 4096 -output_dir /home/ubuntu/data -dm 10 1000 -dm_tol 1.35 -max_giant_rate 20000000 -nbeams 64
    hostargs:
      corr17: -coincidencer 10.41.0.109:12345 -beam 0
      corr18: -coincidencer 10.41.0.109:12346 -beam 64
      corr19: -coincidencer 10.41.0.109:12347 -beam 128
      corr20: -coincidencer 10.41.0.109:12348 -beam 192
  - name: dsaX_writeFil
    cmd: /home/ubuntu/proj/dsa110-shell/dsa110-xengine/src/dsaX_writeFil
    args: -c 27 -i 127.0.0.1 -f /home/ubuntu/data/bsfil -k eada
  - name: gpu_flagger
    cmd: /home/ubuntu/proj/dsa110-shell/dsa110-xengine/src/gpu_flagger
    args: -i fada -o bada -t 4.5 -d -f /home/ubuntu/tmp/spectra.dat -v
  - name: dsaX_simplesplit
    cmd: /home/ubuntu/proj/dsa110-shell/dsa110-xengine/src/dsaX_simplesplit
    args: -c 28 -i dada -o eada -j fada -b
  - name: dsaX_nicdb
    cmd: /home/ubuntu/proj/dsa110-shell/dsa110-xengine/src/dsaX_nicdb
    args: -f /home/ubuntu/proj/dsa110-shell/dsa110-xengine/src/spectrometer_header.txt -d -o dada 
    hostargs:
      corr17: -j 10.41.0.22
      corr18: -j 10.41.0.98
      corr19: -j 10.41.0.105
      corr20: -j 10.41.0.63
      
