# configuration for correlator with original file writing
buffers:
  - k: dada
    b: 1073741824
    n: 4
    c: 0
  - k: eada
    b: 1073741824
    n: 16
    c: 0
  - k: fada
    b: 1073741824
    n: 4
    c: 0
  - k: bada
    b: 1073741824
    n: 4
    c: 0
routines:
  - name: heimdall
    cmd: /home/ubuntu/proj/dsa110-shell/dsa110-mbheimdall/bin/heimdall
    args: -k bada -gpu_id 0 -nsamps_gulp 16384 -output_dir /home/ubuntu/data -dm 50 1500 -dm_tol 1.5 -max_giant_rate 20000000 -nbeams 64
    hostargs:
      corr17: -coincidencer 10.41.0.69:12345 -beam 0
      corr18: -coincidencer 10.41.0.69:12346 -beam 64
      corr19: -coincidencer 10.41.0.69:12347 -beam 128
      corr20: -coincidencer 10.41.0.69:12348 -beam 192
  - name: dsaX_writeFil
    cmd: /home/ubuntu/proj/dsa110-shell/dsa110-xengine/src/dsaX_filTrigger
    args: -c 27 -i 127.0.0.1 -n /home/ubuntu/data/fil -j eada -d 
    hostargs:
      corr17: -n 0
      corr18: -n 64
      corr19: -n 128
      corr20: -n 192
  - name: gpu_flagger
    cmd: /home/ubuntu/proj/dsa110-shell/dsa110-xengine/src/gpu_flagger
    args: -i fada -o bada -t 4.5 -v
    hostargs:
      corr17: -g /home/ubuntu/data/beams_corr17
      corr18: -g /home/ubuntu/data/beams_corr18
      corr19: -g /home/ubuntu/data/beams_corr19
      corr20: -g /home/ubuntu/data/beams_corr20
  - name: dsaX_simplesplit
    cmd: /home/ubuntu/proj/dsa110-shell/dsa110-xengine/src/dsaX_simplesplit
    args: -c 28 -i dada -o eada -j fada -b
  - name: dsaX_nicdb
    cmd: /home/ubuntu/proj/dsa110-shell/dsa110-xengine/src/dsaX_nicdb
    args: -f /home/ubuntu/proj/dsa110-shell/dsa110-xengine/src/spectrometer_header.txt -o dada 
    hostargs:
      corr17: -i 10.41.0.101
      corr18: -i 10.41.0.92
      corr19: -i 10.41.0.103
      corr20: -i 10.41.0.94
      
