# configuration for correlator and beamformer
buffers:
  - k: dada
    b: 75497472 
    n: 10
    c: 0    
  - k: dbda
    b: 75497472 
    n: 8
    c: 0
  - k: dcda
    b: 75497472 
    n: 8
    c: 1
  - k: eada
    b: 402653184
    n: 8
    c: 0
  - k: fada
    b: 51118080
    n: 4
    c: 0
  - k: bada
    b: 1996800
    n: 40
    c: 0
  - k: cada
    b: 1572864
    n: 4
    c: 1
routines:
  - name: dada_dbnull
    cmd: dada_dbnull
    args: -k bada
  - name: dada_dbnull2
    cmd: dada_dbnull
    args: -k cada
  - name: dsaX_wrangle
    cmd: /home/ubuntu/proj/dsa110-shell/dsa110-xengine/src/dsaX_wrangle
    args: -i fada -o bada
  - name: dsaX_beamformer
    cmd: /home/ubuntu/proj/dsa110-shell/dsa110-xengine/src/dsaX_beamformer
    args: -c 30 -f /home/ubuntu/proj/dsa110-shell/dsa110-xengine/utils/antennas.out -i dcda -o cada
  - name: dsaX_xgpu
    cmd: /home/ubuntu/proj/dsa110-shell/dsa110-xengine/src/dsaX_xgpu
    args: -t 4 -i eada -o fada -c 2
  - name: dsaX_reorder_raw
    cmd: /home/ubuntu/proj/dsa110-shell/dsa110-xengine/src/dsaX_reorder_raw
    args: -t 16 -i dbda -o eada
  - name: dsaX_split
    cmd: /home/ubuntu/proj/dsa110-shell/dsa110-xengine/src/dsaX_split
    args: -b -i dada -o dbda -j dcda -c 19 -r -d
  - name: dada_junkdb
    cmd: dada_junkdb
    args: -t 1000 -k dada -r 560 /home/ubuntu/proj/dsa110-shell/dsa110-xengine/src/correlator_header_dsaX.txt
