FLAG1 48
FLAG2 96
INPUT FILE
INPUT_PATH /home/ubuntu/scratch/image_large.txt
DM_MIN 50
DM_MAX 3000
WIDTH_MIN 1
WIDTH_MAX 128
SNR 7.0
GULP 16384
OUTPUT FILE
HOST 10.42.0.90
PORT 12345
GPU 1
BEAM0 0
BEAM_OFFSET 0
OUTPUTPATH test.out
SPECFLAGS spec.out
BEAMFLAGS beam.out
SCRUNCH 3
128 2 6.0 1
8 8 7.0 1
128 1 6.0 1